server:
  port: 5012

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airline_seat_db
    username: myprojects
    password: myprojects

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: seat-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true