server:
  port: 5001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airline_location_db
    username: myprojects
    password: myprojects

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true